//
//  DARK.h
//  MicroSoccer5
//
//  Created by Trevor Delves on 09/04/2016.
//  Copyright © 2016 Apportable. All rights reserved.
//

#ifndef England_h
#define England_h

#include "PlayerStats.h"

//
#define WHITE_PLAYER_KEEPER_BROWN_HAIR      @SKIN_WHITE,  @EXTRA_DARK_BROWN


#define WHITE_PLAYER_LIGHT_BROWN_HAIR       @SKIN_WHITE,  @LIGHT_BROWN
#define WHITE_PLAYER_DARK_BROWN_HAIR        @SKIN_WHITE,  @DARK_BROWN
#define WHITE_PLAYER_BLACK_HAIR             @SKIN_WHITE,  @BLACK

#define LIGHT_PLAYER_GINGER_HAIR            @LIGHT_BROWN,  @GINGER
#define LIGHT_PLAYER_DARK_HAIR              @LIGHT_BROWN,  @DARK_BROWN
#define LIGHT_PLAYER_BLK_HAIR               @LIGHT_BROWN,  @BLACK

#define DARK_PLAYER_GINGER_HAIR             @DARK_BROWN,  @GINGER
#define DARK_PLAYER_BROWN_HAIR              @DARK_BROWN,  @EXTRA_DARK_BROWN
#define DARK_PLAYER_BLACK_HAIR              @DARK_BROWN,  @BLACK



// ENGLAND
#define ENGLAND_TEAM_INFO @"ENGLAND",@"ENG",@IVORY_WHITE,@IVORY_WHITE,@ENGLAND_BLUE,@BLUE

// FRANCE
#define FRANCE_TEAM_INFO @"FRANCE",@"FRA",@BLUE,@BLUE,@BLUE,@WHITE

// ITALY
#define ITALY_TEAM_INFO @"ITALY",@"ITA",@ITALIAN_BLUE,@ITALIAN_BLUE,@ITALIAN_BLUE,@WHITE

// SPAIN
#define SPAIN_TEAM_INFO @"SPAIN",@"SPA",@SPANISH_RED,@SPANISH_RED,@SPANISH_RED,@WHITE

// GERMANY
#define GERMANY_TEAM_INFO @"GERMANY",@"GER",@LIGHT_GRAY,@LIGHT_GRAY,@GERMANY_GREEN,@WHITE

// HOLLAND
#define HOLLAND_TEAM_INFO @"HOLLAND",@"HOL",@ORANGE,@ORANGE,@ORANGE,@BLACK

// BRAZIL
#define BRAZIL_TEAM_INFO @"BRAZIL",@"BRA",@BRAZIL_YELLOW,@BRAZIL_YELLOW,@BRAZIL_YELLOW,@LIGHT_BLUE
//#define BRAZIL_TEAM_INFO @"INTER",@"INT",@BLACK,@BLUE,@BLUE,@BLUE

// ARGENTINA
#define ARGENTINA_TEAM_INFO @"ARGENTINA",@"ARG",@WHITE,@LIGHT_BLUE,@LIGHT_BLUE,@BLACK

// GHANA
#define GHANA_TEAM_INFO @"GHANA",@"GHA",@WHITE,@BRAZIL_YELLOW,@WHITE,@WHITE

// IVORYCOAST
#define IVORYCOAST_TEAM_INFO @"NIGERIA",@"NIG",@IVORY_COAST_GREEN,@IVORY_COAST_GREEN,@IVORY_COAST_GREEN,@GREEN

// PORTUGAL
#define PORTUGAL_TEAM_INFO @"PORTUGAL",@"POR",@PORTUGAL_DARK_GREEN,@PORTUGAL_DARK_GREEN,@PORTUGAL_LIGHT_GREEN,@RED

// BELGIUM
#define BELGIUM_TEAM_INFO @"BELGIUM",@"BEL",@BELGIAN_BLUE,@BLACK,@BELGIAN_BLUE,@RED

// USA
#define USA_TEAM_INFO @"USA",@"USA",@BLACK,@RED,@BLUE,@RED

// JAPAN
#define JAPAN_TEAM_INFO @"JAPAN",@"JPN",@JAPAN_YELLOW,@JAPAN_YELLOW,@JAPAN_YELLOW,@YELLOW

// WALES
#define WALES_TEAM_INFO @"WALES",@"WAL",@BLACK,@BLACK,@GREEN,@YELLOW


///////////////////////////////

// ENGLAND
#define ENGLAND_PLAYER_STATS1   @"J.PICKFORD",        WHITE_PLAYER_KEEPER_BROWN_HAIR,            @KEEPER, STRONG_STATS
#define ENGLAND_PLAYER_STATS2   @"J.STONE",    LIGHT_PLAYER_DARK_HAIR,              @DEFENDER, MEDIUM_STATS
#define ENGLAND_PLAYER_STATS3   @"K.WALKER",      LIGHT_PLAYER_DARK_HAIR,             @DEFENDER, STRONG_STATS
#define ENGLAND_PLAYER_STATS4   @"D.ROSE",        DARK_PLAYER_BLACK_HAIR,             @DEFENDER, STRONG_STATS
#define ENGLAND_PLAYER_STATS5   @"R.BARKLEY",     WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, WEAK_STATS
#define ENGLAND_PLAYER_STATS6   @"D.ALLI",        LIGHT_PLAYER_DARK_HAIR,             @MIDFIELD, EXTRA_STRONG_STATS
#define ENGLAND_PLAYER_STATS7   @"R.STERLING",   DARK_PLAYER_BLACK_HAIR,             @STRIKER, SUPER_EXTRA_STRONG_STATS
#define ENGLAND_PLAYER_STATS8   @"J.VARDY",       WHITE_PLAYER_LIGHT_BROWN_HAIR,       @STRIKER, EXTRA_STRONG_STATS
#define ENGLAND_PLAYER_STATS9   @"H.KANE",        WHITE_PLAYER_LIGHT_BROWN_HAIR,       @STRIKER, EXTRA_STRONG_STATS
#define ENGLAND_PLAYER_STATS10  @"H.MAGUIRE",    WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, MEDIUM_STATS
#define ENGLAND_PLAYER_STATS11  @"B.CHILWELL",      WHITE_PLAYER_DARK_BROWN_HAIR,    @DEFENDER, STRONG_STATS
#define ENGLAND_PLAYER_STATS12  @"D.RICE",       WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, STRONG_STATS
#define ENGLAND_PLAYER_STATS13  @"J.HENDERSON",    WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, MEDIUM_STATS
#define ENGLAND_PLAYER_STATS14  @"E.DIER",      WHITE_PLAYER_DARK_BROWN_HAIR,             @MIDFIELD, MEDIUM_STATS
#define ENGLAND_PLAYER_STATS15  @"C.HUDSON-ADOI",   DARK_PLAYER_BLACK_HAIR,       @MIDFIELD, STRONG_STATS
#define ENGLAND_PLAYER_STATS16  @"J.SANCHO",    DARK_PLAYER_BLACK_HAIR,             @STRIKER, STRONG_STATS
#define ENGLAND_PLAYER_STATS17  @"M.RASHFORD",     DARK_PLAYER_BLACK_HAIR,       @STRIKER, STRONG_STATS
#define ENGLAND_PLAYER_STATS18  @"C.WILSON",    LIGHT_PLAYER_DARK_HAIR,             @STRIKER, MEDIUM_STATS



// FRANCE
#define FRANCE_PLAYER_STATS1  @"H.LLORIS",       WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define FRANCE_PLAYER_STATS2  @"P.EVRA",         DARK_PLAYER_BLACK_HAIR,             @DEFENDER, MEDIUM_STATS
#define FRANCE_PLAYER_STATS3  @"L.KOSCIELNY",    WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, STRONG_STATS
#define FRANCE_PLAYER_STATS4  @"B.SAGNA",        DARK_PLAYER_BROWN_HAIR,             @DEFENDER, MEDIUM_STATS
#define FRANCE_PLAYER_STATS5  @"Y.CABAYE",       WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, STRONG_STATS
#define FRANCE_PLAYER_STATS6  @"P.POGBA",        DARK_PLAYER_BLACK_HAIR,             @MIDFIELD, EXTRA_STRONG_STATS
#define FRANCE_PLAYER_STATS7  @"N.KANTE",        DARK_PLAYER_BLACK_HAIR,             @MIDFIELD, EXTRA_STRONG_STATS
#define FRANCE_PLAYER_STATS8  @"D.PAYET",        LIGHT_PLAYER_DARK_HAIR,             @STRIKER, EXTRA_STRONG_STATS
#define FRANCE_PLAYER_STATS9  @"A.GRIEZMAN",     DARK_PLAYER_BROWN_HAIR,             @DEFENDER, STRONG_STATS
#define FRANCE_PLAYER_STATS10 @"R.VARANE",       DARK_PLAYER_BLACK_HAIR,             @DEFENDER, STRONG_STATS
#define FRANCE_PLAYER_STATS11 @"M.SAKHO",        DARK_PLAYER_BROWN_HAIR,             @DEFENDER, STRONG_STATS
#define FRANCE_PLAYER_STATS12 @"J.MATHIEU",      WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, WEAK_STATS
#define FRANCE_PLAYER_STATS13 @"L.DIARRA",       DARK_PLAYER_BROWN_HAIR,             @MIDFIELD, STRONG_STATS
#define FRANCE_PLAYER_STATS14 @"M.SISSOKO",      DARK_PLAYER_BROWN_HAIR,             @MIDFIELD, MEDIUM_STATS
#define FRANCE_PLAYER_STATS15 @"B.MATUIDI",      DARK_PLAYER_BROWN_HAIR,             @MIDFIELD, STRONG_STATS
#define FRANCE_PLAYER_STATS16 @"A.MARTIAL",      DARK_PLAYER_BROWN_HAIR,             @STRIKER, WEAK_STATS
#define FRANCE_PLAYER_STATS17 @"K.MBAPPE",       DARK_PLAYER_BROWN_HAIR,             @STRIKER, EXTRA_STRONG_STATS
#define FRANCE_PLAYER_STATS18 @"A.GIGNAC",       WHITE_PLAYER_DARK_BROWN_HAIR,       @STRIKER, WEAK_STATS


// ITALY
#define ITALY_PLAYER_STATS1  @"S.SIRIGU",        WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define ITALY_PLAYER_STATS2  @"A.ROMAGNOLI",       LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, MEDIUM_STATS
#define ITALY_PLAYER_STATS3  @"L.SPINAZOLLA",     LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, WEAK_STATS
#define ITALY_PLAYER_STATS4  @"C.BIRAGHI",        LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, MEDIUM_STATS
#define ITALY_PLAYER_STATS5  @"JORGINHO",         LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define ITALY_PLAYER_STATS6  @"M.VERRATTI",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define ITALY_PLAYER_STATS7  @"M.BARELLA",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define ITALY_PLAYER_STATS8  @"L.PAVOLETTI",          LIGHT_PLAYER_DARK_HAIR,     @STRIKER, EXTRA_STRONG_STATS
#define ITALY_PLAYER_STATS9  @"K.LASAGNA",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, MEDIUM_STATS
#define ITALY_PLAYER_STATS10 @"L.BONUCCI",      LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, WEAK_STATS
#define ITALY_PLAYER_STATS11 @"G.CHIELLINI",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, MEDIUM_STATS
#define ITALY_PLAYER_STATS12 @"A.IZZO",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define ITALY_PLAYER_STATS13 @"C.IMMOBILE",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, STRONG_STATS
#define ITALY_PLAYER_STATS14 @"M.POLITANO",       LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define ITALY_PLAYER_STATS15 @"B.CHRISTANTE",     LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define ITALY_PLAYER_STATS16 @"E.GIACCHE",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, STRONG_STATS
#define ITALY_PLAYER_STATS17 @"M.KEANE",        DARK_PLAYER_BLACK_HAIR,     @STRIKER, STRONG_STATS
#define ITALY_PLAYER_STATS18 @"F.QUAGLIARELLA",        LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS

// SPAIN
#define SPAIN_PLAYER_STATS1  @"D.DEGEA",        WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define SPAIN_PLAYER_STATS2  @"S.RAMOS",        LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, EXTRA_STRONG_STATS
#define SPAIN_PLAYER_STATS3  @"G.PIQUE",        LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define SPAIN_PLAYER_STATS4  @"J.ALBA",         LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, WEAK_STATS
#define SPAIN_PLAYER_STATS5  @"S.NIGUEZ",       LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define SPAIN_PLAYER_STATS6  @"D.SILVA",        LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define SPAIN_PLAYER_STATS7  @"S.BUSQUETS",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define SPAIN_PLAYER_STATS8  @"D.COSTA",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, WEAK_STATS
#define SPAIN_PLAYER_STATS9  @"A.MORATA",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, MEDIUM_STATS
#define SPAIN_PLAYER_STATS10 @"C.AZPILIC",      LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, WEAK_STATS
#define SPAIN_PLAYER_STATS11 @"I.MARTINEZ",       LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define SPAIN_PLAYER_STATS12 @"D.CARVAJAL",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define SPAIN_PLAYER_STATS13 @"S.ROBERTO",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define SPAIN_PLAYER_STATS14 @"D.CEBALLOS",     LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, STRONG_STATS
#define SPAIN_PLAYER_STATS15 @"ISCO",           LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define SPAIN_PLAYER_STATS16 @"I.ASPAS",         LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define SPAIN_PLAYER_STATS17 @"RODRIGO",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS
#define SPAIN_PLAYER_STATS18 @"M.ASESNSIO",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS


// GERMANY
#define GERMANY_PLAYER_STATS1 @"M.NEUER",       WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define GERMANY_PLAYER_STATS2 @"M.HUMMELS",     WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, STRONG_STATS
#define GERMANY_PLAYER_STATS3 @"N.SULE",         WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, MEDIUM_STATS
#define GERMANY_PLAYER_STATS4 @"A.RUDIGER",     WHITE_PLAYER_LIGHT_BROWN_HAIR,       @DEFENDER, EXTRA_STRONG_STATS
#define GERMANY_PLAYER_STATS5 @"T.KROOS",       WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define GERMANY_PLAYER_STATS6 @"J.KIMMICH",      LIGHT_PLAYER_DARK_HAIR,            @MIDFIELD, MEDIUM_STATS
#define GERMANY_PLAYER_STATS7 @"SANE",          LIGHT_PLAYER_DARK_HAIR,             @MIDFIELD, EXTRA_STRONG_STATS
#define GERMANY_PLAYER_STATS8 @"M.UTH",        WHITE_PLAYER_LIGHT_BROWN_HAIR,     @STRIKER, EXTRA_STRONG_STATS
#define GERMANY_PLAYER_STATS9 @"T.MULLER",       WHITE_PLAYER_BLACK_HAIR,            @STRIKER, MEDIUM_STATS
#define GERMANY_PLAYER_STATS10 @"M.GINTER",     WHITE_PLAYER_LIGHT_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define GERMANY_PLAYER_STATS11 @"S.RUDY",       WHITE_PLAYER_LIGHT_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define GERMANY_PLAYER_STATS12 @"T.KEHRER",     LIGHT_PLAYER_DARK_HAIR,            @DEFENDER, STRONG_STATS
#define GERMANY_PLAYER_STATS13 @"M.GINTER",    WHITE_PLAYER_LIGHT_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define GERMANY_PLAYER_STATS14 @"L.GORETZKA",   WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define GERMANY_PLAYER_STATS15 @"M.REUS",       WHITE_PLAYER_BLACK_HAIR,            @MIDFIELD, STRONG_STATS
#define GERMANY_PLAYER_STATS16 @"J.DRAXLER",    WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, STRONG_STATS
#define GERMANY_PLAYER_STATS17 @"T.WERNER",    WHITE_PLAYER_LIGHT_BROWN_HAIR,     @STRIKER, STRONG_STATS
#define GERMANY_PLAYER_STATS18 @"G.NABRY",      LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS

// USA
#define USA_PLAYER_STATS1 @"Z.STEFFEN",       WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define USA_PLAYER_STATS2 @"D.YEDLIN",     LIGHT_PLAYER_DARK_HAIR,       @DEFENDER, STRONG_STATS
#define USA_PLAYER_STATS3 @"K.ACOSTA",    LIGHT_PLAYER_DARK_HAIR,       @DEFENDER, WEAK_STATS
#define USA_PLAYER_STATS4 @"M.MIAZGA",     LIGHT_PLAYER_DARK_HAIR,            @DEFENDER, EXTRA_STRONG_STATS
#define USA_PLAYER_STATS5 @"M.BRADLEY",       WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define USA_PLAYER_STATS6 @"T.ADAMS",      DARK_PLAYER_BLACK_HAIR,            @MIDFIELD, MEDIUM_STATS
#define USA_PLAYER_STATS7 @"D.LOVITZ",    WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define USA_PLAYER_STATS8 @"G.ZARDES",        WHITE_PLAYER_LIGHT_BROWN_HAIR,     @STRIKER, EXTRA_STRONG_STATS
#define USA_PLAYER_STATS9 @"P.ARRIOLA",       LIGHT_PLAYER_DARK_HAIR,            @STRIKER, MEDIUM_STATS
#define USA_PLAYER_STATS10 @"T.REAM",     LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define USA_PLAYER_STATS11 @"J.BROOKS",       WHITE_PLAYER_LIGHT_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define USA_PLAYER_STATS12 @"C.VICKERS",  WHITE_PLAYER_BLACK_HAIR,            @DEFENDER, STRONG_STATS
#define USA_PLAYER_STATS13 @"C.BAIRD",    WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define USA_PLAYER_STATS14 @"C.PULISIC",   WHITE_PLAYER_LIGHT_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define USA_PLAYER_STATS15 @"C.ROLDAN",       WHITE_PLAYER_BLACK_HAIR,            @MIDFIELD, STRONG_STATS
#define USA_PLAYER_STATS16 @"T.WEAH",    DARK_PLAYER_BLACK_HAIR,       @STRIKER, STRONG_STATS
#define USA_PLAYER_STATS17 @"B.WOOD",    WHITE_PLAYER_LIGHT_BROWN_HAIR,     @STRIKER, STRONG_STATS
#define USA_PLAYER_STATS18 @"J.GREEN",      WHITE_PLAYER_LIGHT_BROWN_HAIR,     @STRIKER, STRONG_STATS



// HOLLAND
#define HOLLAND_PLAYER_STATS1  @"C.CILLISSEN",        DARK_PLAYER_BLACK_HAIR,           @KEEPER, MEDIUM_STATS
#define HOLLAND_PLAYER_STATS2  @"D.BLIND",       WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define HOLLAND_PLAYER_STATS3  @"V.DIJK",       LIGHT_PLAYER_DARK_HAIR,             @DEFENDER, SUPER_EXTRA_STRONG_STATS
#define HOLLAND_PLAYER_STATS4  @"D.DUMPHRIES",   WHITE_PLAYER_DARK_BROWN_HAIR,         @DEFENDER, MEDIUM_STATS
#define HOLLAND_PLAYER_STATS5  @"F.DEJON",      WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define HOLLAND_PLAYER_STATS6  @"G.WINALDUM",   DARK_PLAYER_BROWN_HAIR,           @MIDFIELD, STRONG_STATS
#define HOLLAND_PLAYER_STATS7  @"M.V.GINKEL",    WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define HOLLAND_PLAYER_STATS8  @"J.DILROSUN",   WHITE_PLAYER_DARK_BROWN_HAIR,     @STRIKER, STRONG_STATS
#define HOLLAND_PLAYER_STATS9  @"M.DEPAY",       LIGHT_PLAYER_DARK_HAIR,           @STRIKER, STRONG_STATS
#define HOLLAND_PLAYER_STATS10 @"M.DELIGT",     WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, MEDIUM_STATS
#define HOLLAND_PLAYER_STATS11 @"K.TETE",       WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define HOLLAND_PLAYER_STATS12 @"N.AKE",        LIGHT_PLAYER_DARK_HAIR,           @DEFENDER, MEDIUM_STATS
#define HOLLAND_PLAYER_STATS13 @"Q.PROMES",      DARK_PLAYER_BLACK_HAIR,           @MIDFIELD, STRONG_STATS
#define HOLLAND_PLAYER_STATS14 @"W.SNEIJDER",     WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define HOLLAND_PLAYER_STATS15 @"M.DEROON",      WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, WEAK_STATS
#define HOLLAND_PLAYER_STATS16 @"L.JONG",        DARK_PLAYER_BROWN_HAIR,           @STRIKER, MEDIUM_STATS
#define HOLLAND_PLAYER_STATS17 @"R.BABEL",    DARK_PLAYER_BLACK_HAIR,           @STRIKER, STRONG_STATS
#define HOLLAND_PLAYER_STATS18 @"J.KLUIVERT",     WHITE_PLAYER_DARK_BROWN_HAIR,     @STRIKER, MEDIUM_STATS


// INTER
//#define BRAZIL_PLAYER_STATS1  @"S.HANDANOVIC",        DARK_PLAYER_BLACK_HAIR,         @KEEPER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS2  @"MIRANDA",        LIGHT_PLAYER_DARK_HAIR,         @DEFENDER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS3  @"A.RANOCCHIA",         DARK_PLAYER_BROWN_HAIR,         @DEFENDER, MEDIUM_STATS
//#define BRAZIL_PLAYER_STATS4  @"G.MEDEL",        DARK_PLAYER_BLACK_HAIR,         @DEFENDER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS5  @"E.BANEGA",      DARK_PLAYER_BROWN_HAIR,         @MIDFIELD, MEDIUM_STATS
//#define BRAZIL_PLAYER_STATS6  @"J.MARIO",          DARK_PLAYER_BROWN_HAIR,         @MIDFIELD, WEAK_STATS
//#define BRAZIL_PLAYER_STATS7  @"A.CANDREVA",        DARK_PLAYER_BLACK_HAIR,         @MIDFIELD, EXTRA_STRONG_STATS
//#define BRAZIL_PLAYER_STATS8  @"I.PERISIC",    LIGHT_PLAYER_DARK_HAIR,         @MIDFIELD, WEAK_STATS
//#define BRAZIL_PLAYER_STATS9  @"M.ICARDI",         LIGHT_PLAYER_DARK_HAIR,         @STRIKER, SUPER_EXTRA_STRONG_STATS
//#define BRAZIL_PLAYER_STATS10 @"D.SANTON",           LIGHT_PLAYER_DARK_HAIR,         @STRIKER, WEAK_STATS
//#define BRAZIL_PLAYER_STATS11 @"D.D'AMBROSIO",       DARK_PLAYER_BLACK_HAIR,         @DEFENDER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS12 @"M.BROZOVIC",         WHITE_PLAYER_DARK_BROWN_HAIR,   @DEFENDER, MEDIUM_STATS
//#define BRAZIL_PLAYER_STATS13 @"L.ZANTA",        DARK_PLAYER_BLACK_HAIR,         @DEFENDER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS14 @"F.MELO",        DARK_PLAYER_BLACK_HAIR,         @MIDFIELD, MEDIUM_STATS
//#define BRAZIL_PLAYER_STATS15 @"EDER",     WHITE_PLAYER_DARK_BROWN_HAIR,   @MIDFIELD, WEAK_STATS
//#define BRAZIL_PLAYER_STATS16 @"J.BIABINAY",           DARK_PLAYER_BROWN_HAIR,         @STRIKER, STRONG_STATS
//#define BRAZIL_PLAYER_STATS17 @"S.JOVETIC",           DARK_PLAYER_BLACK_HAIR,         @STRIKER, MEDIUM_STATS
//#define BRAZIL_PLAYER_STATS18 @"R.PALACIO",     DARK_PLAYER_BROWN_HAIR,         @STRIKER, WEAK_STATS


// BRAZIL
#define BRAZIL_PLAYER_STATS1  @"ALISSON",        DARK_PLAYER_BLACK_HAIR,         @KEEPER, STRONG_STATS
#define BRAZIL_PLAYER_STATS2  @"MIRANDA",        LIGHT_PLAYER_DARK_HAIR,         @DEFENDER, STRONG_STATS
#define BRAZIL_PLAYER_STATS3  @"T.SILVA",        DARK_PLAYER_BROWN_HAIR,         @DEFENDER, STRONG_STATS
#define BRAZIL_PLAYER_STATS4  @"MARCELO",        LIGHT_PLAYER_DARK_HAIR,         @DEFENDER, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS5  @"D.GUSTAVO",      DARK_PLAYER_BROWN_HAIR,         @MIDFIELD, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS6  @"PAULINHO",       DARK_PLAYER_BROWN_HAIR,         @MIDFIELD, WEAK_STATS
#define BRAZIL_PLAYER_STATS7  @"WILLIAN",        DARK_PLAYER_BLACK_HAIR,         @MIDFIELD, STRONG_STATS
#define BRAZIL_PLAYER_STATS8  @"FERNANDO",       LIGHT_PLAYER_DARK_HAIR,         @MIDFIELD, EXTRA_STRONG_STATS
#define BRAZIL_PLAYER_STATS9  @"NEYMAR",         LIGHT_PLAYER_DARK_HAIR,         @STRIKER, SUPER_EXTRA_STRONG_STATS
#define BRAZIL_PLAYER_STATS10 @"G.JESUS",        LIGHT_PLAYER_DARK_HAIR,         @STRIKER, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS11 @"A.SANDRO",       DARK_PLAYER_BLACK_HAIR,         @DEFENDER, STRONG_STATS
#define BRAZIL_PLAYER_STATS12 @"DANILO",         WHITE_PLAYER_DARK_BROWN_HAIR,   @DEFENDER, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS13 @"MARQUINHOS",     DARK_PLAYER_BLACK_HAIR,         @DEFENDER, STRONG_STATS
#define BRAZIL_PLAYER_STATS14 @"CASEMIRO",       DARK_PLAYER_BLACK_HAIR,         @MIDFIELD, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS15 @"P.COUTINHO",     WHITE_PLAYER_DARK_BROWN_HAIR,   @MIDFIELD, MEDIUM_STATS
#define BRAZIL_PLAYER_STATS16 @"F.ANDERSON",     LIGHT_PLAYER_DARK_HAIR,         @STRIKER, EXTRA_STRONG_STATS
#define BRAZIL_PLAYER_STATS17 @"RICHARLISON",    LIGHT_PLAYER_DARK_HAIR,         @STRIKER, STRONG_STATS
#define BRAZIL_PLAYER_STATS18 @"FIRMINO",        LIGHT_PLAYER_DARK_HAIR,         @STRIKER, STRONG_STATS


// ARGENTINA
#define ARGENTINA_PLAYER_STATS1  @"S.ROMERO",       WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS2  @"G.PEZZELLA",     LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS3  @"N.MAKSIMOVIC",         LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, MEDIUM_STATS
#define ARGENTINA_PLAYER_STATS4  @"M.MEZA",         LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS5  @"J.MASCHERANO",   LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define ARGENTINA_PLAYER_STATS6  @"A.D.MARIA",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, STRONG_STATS
#define ARGENTINA_PLAYER_STATS7  @"N.TAGLIAFICO",      LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS8  @"L.MESSI",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, SUPER_EXTRA_STRONG_STATS
#define ARGENTINA_PLAYER_STATS9  @"S.AGUERO",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, WEAK_STATS
#define ARGENTINA_PLAYER_STATS10 @"N.OTAMENDI",     LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, MEDIUM_STATS
#define ARGENTINA_PLAYER_STATS11 @"M.ROJO",      LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS12 @"M.RODRIGEZ",     LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define ARGENTINA_PLAYER_STATS13 @"R.PEREYRA",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define ARGENTINA_PLAYER_STATS14 @"M.ICARDI",       LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS15 @"G.MARTINEZ",       LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define ARGENTINA_PLAYER_STATS16 @"L.MARTINEZ",     LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS17 @"C.PAVON",        LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define ARGENTINA_PLAYER_STATS18 @"P.DYBALA",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS


// GHANA
#define GHANA_PLAYER_STATS1 @"R.OFORI",      DARK_PLAYER_BLACK_HAIR,     @KEEPER, STRONG_STATS
#define GHANA_PLAYER_STATS2 @"K.ASOMOAH",         DARK_PLAYER_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define GHANA_PLAYER_STATS3 @"N.OPOKU",        DARK_PLAYER_BLACK_HAIR,     @DEFENDER, WEAK_STATS
#define GHANA_PLAYER_STATS4 @"J.BOYE",          DARK_PLAYER_BROWN_HAIR,     @DEFENDER, MEDIUM_STATS
#define GHANA_PLAYER_STATS5 @"K.OPPONG",       DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, STRONG_STATS
#define GHANA_PLAYER_STATS6 @"E.AGYEMANG",      DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, WEAK_STATS
#define GHANA_PLAYER_STATS7 @"C.ATSU",          DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define GHANA_PLAYER_STATS8 @"J.AYEW",          DARK_PLAYER_BROWN_HAIR,     @STRIKER, STRONG_STATS
#define GHANA_PLAYER_STATS9 @"A.GYAN",          DARK_PLAYER_BLACK_HAIR,     @STRIKER, WEAK_STATS
#define GHANA_PLAYER_STATS10 @"A.YIADOM",       DARK_PLAYER_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define GHANA_PLAYER_STATS11 @"A.FRIMPONG",      DARK_PLAYER_BLACK_HAIR,     @DEFENDER, STRONG_STATS
#define GHANA_PLAYER_STATS12 @"N.KASSIM",      DARK_PLAYER_BLACK_HAIR,     @DEFENDER, MEDIUM_STATS
#define GHANA_PLAYER_STATS13 @"C.ATSU",       DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, WEAK_STATS
#define GHANA_PLAYER_STATS14 @"J.SCHLUPP",       DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, MEDIUM_STATS
#define GHANA_PLAYER_STATS15 @"A.WAKASO",        DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, STRONG_STATS
#define GHANA_PLAYER_STATS16 @"C.EKUBAN",       DARK_PLAYER_BLACK_HAIR,     @STRIKER, MEDIUM_STATS
#define GHANA_PLAYER_STATS17 @"E.BOATENG",   DARK_PLAYER_BROWN_HAIR,     @STRIKER, WEAK_STATS
#define GHANA_PLAYER_STATS18 @"K.APPIAH",        DARK_PLAYER_BLACK_HAIR,     @STRIKER, STRONG_STATS

// NIGERIA
#define IVORYCOAST_PLAYER_STATS1 @"D.AKPEYI",      DARK_PLAYER_BLACK_HAIR,     @KEEPER, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS2 @"W.T.EKONG",         DARK_PLAYER_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS3 @"B.IDOWU",        DARK_PLAYER_BLACK_HAIR,     @DEFENDER, WEAK_STATS
#define IVORYCOAST_PLAYER_STATS4 @"L.BALOGUN",          DARK_PLAYER_BROWN_HAIR,     @DEFENDER, MEDIUM_STATS
#define IVORYCOAST_PLAYER_STATS5 @"J.MIKEL",       DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS6 @"A.IWOBI",      DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, WEAK_STATS
#define IVORYCOAST_PLAYER_STATS7 @"O.ETEBO",          DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS8 @"A.MUSA",          DARK_PLAYER_BROWN_HAIR,     @STRIKER, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS9 @"K.IHEANACHO",          DARK_PLAYER_BLACK_HAIR,     @STRIKER, WEAK_STATS
#define IVORYCOAST_PLAYER_STATS10 @"A.SHEHU",       DARK_PLAYER_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS11 @"S.AJAYI",      DARK_PLAYER_BLACK_HAIR,     @DEFENDER, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS12 @"K.OMERUO",      DARK_PLAYER_BLACK_HAIR,     @DEFENDER, MEDIUM_STATS
#define IVORYCOAST_PLAYER_STATS13 @"V.MOSES",       DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, WEAK_STATS
#define IVORYCOAST_PLAYER_STATS14 @"O.NDIDI",       DARK_PLAYER_BROWN_HAIR,     @MIDFIELD, MEDIUM_STATS
#define IVORYCOAST_PLAYER_STATS15 @"J.COLLINS",        DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, STRONG_STATS
#define IVORYCOAST_PLAYER_STATS16 @"O.IGHALO",       DARK_PLAYER_BLACK_HAIR,     @STRIKER, MEDIUM_STATS
#define IVORYCOAST_PLAYER_STATS17 @"H.ONYEKURU",   DARK_PLAYER_BROWN_HAIR,     @STRIKER, WEAK_STATS
#define IVORYCOAST_PLAYER_STATS18 @"M.DADDY",        DARK_PLAYER_BLACK_HAIR,     @STRIKER, STRONG_STATS


// PORTUGAL
#define PORTUGAL_PLAYER_STATS1  @"R.PATRICIO",     WHITE_PLAYER_KEEPER_BROWN_HAIR,     @KEEPER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS2  @"PEPE",        LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, MEDIUM_STATS
#define PORTUGAL_PLAYER_STATS3  @"J.CANCELO",        LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS4  @"J.FONTE",         LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, WEAK_STATS
#define PORTUGAL_PLAYER_STATS5  @"A.SILVA",     LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define PORTUGAL_PLAYER_STATS6  @"A.GOMES",        LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define PORTUGAL_PLAYER_STATS7  @"BRUMA",      LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS8  @"A.M.SILVA",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, EXTRA_STRONG_STATS
#define PORTUGAL_PLAYER_STATS9  @"C.RONALDO",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, SUPER_EXTRA_STRONG_STATS
#define PORTUGAL_PLAYER_STATS10 @"M.RUI",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, WEAK_STATS
#define PORTUGAL_PLAYER_STATS11 @"R.GUERREIRO",       LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS12 @"A.DIAS",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS13 @"D.PEREIRA",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define PORTUGAL_PLAYER_STATS14 @"W.CARVALHO",     DARK_PLAYER_BLACK_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define PORTUGAL_PLAYER_STATS15 @"J.MARIO",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define PORTUGAL_PLAYER_STATS16 @"R.SILVA",         LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS17 @"W.D.SOUSA",      LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS
#define PORTUGAL_PLAYER_STATS18 @"B.SILVA",            LIGHT_PLAYER_DARK_HAIR,     @STRIKER, EXTRA_STRONG_STATS


// BELGIUM
#define BELGIUM_PLAYER_STATS1  @"T.COURTOIS",        DARK_PLAYER_BLACK_HAIR,           @KEEPER, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS2  @"T.ALDERWIRE",       WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define BELGIUM_PLAYER_STATS3  @"T.MEUNIER",       WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, STRONG_STATS
#define BELGIUM_PLAYER_STATS4  @"J.VERTONGE",       WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS5  @"K.BRUYNE",     WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, EXTRA_STRONG_STATS
#define BELGIUM_PLAYER_STATS6  @"M.DEMBELE",   DARK_PLAYER_BROWN_HAIR,           @MIDFIELD, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS7  @"E.HAZARD",    WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, SUPER_EXTRA_STRONG_STATS
#define BELGIUM_PLAYER_STATS8  @"R.LUKAKU",   DARK_PLAYER_BROWN_HAIR,           @STRIKER, EXTRA_STRONG_STATS
#define BELGIUM_PLAYER_STATS9  @"C.BENTEKE",       DARK_PLAYER_BROWN_HAIR,           @STRIKER, STRONG_STATS
#define BELGIUM_PLAYER_STATS10 @"J.LUKAKU",     DARK_PLAYER_BROWN_HAIR,             @DEFENDER, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS11 @"D.BOYATA",   DARK_PLAYER_BROWN_HAIR,     @DEFENDER, WEAK_STATS
#define BELGIUM_PLAYER_STATS12 @"T.VERMAELE",    WHITE_PLAYER_DARK_BROWN_HAIR,     @DEFENDER, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS13 @"A.WITSEL",      DARK_PLAYER_BLACK_HAIR,           @MIDFIELD, STRONG_STATS
#define BELGIUM_PLAYER_STATS14 @"Y.TIELEMANS",     WHITE_PLAYER_DARK_BROWN_HAIR,     @MIDFIELD, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS15 @"L.DENDONCKER",    WHITE_PLAYER_DARK_BROWN_HAIR,            @MIDFIELD, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS16 @"D.MERTENS",        DARK_PLAYER_BROWN_HAIR,           @STRIKER, MEDIUM_STATS
#define BELGIUM_PLAYER_STATS17 @"M.BATSHUA",    DARK_PLAYER_BLACK_HAIR,           @STRIKER, STRONG_STATS
#define BELGIUM_PLAYER_STATS18 @"D.ORIGI",     DARK_PLAYER_BLACK_HAIR,              @STRIKER, MEDIUM_STATS

// JAPAN
#define JAPAN_PLAYER_STATS1  @"E.KAWASHI",     LIGHT_PLAYER_DARK_HAIR,     @KEEPER, STRONG_STATS
#define JAPAN_PLAYER_STATS2  @"H.SAKAI",        LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, MEDIUM_STATS
#define JAPAN_PLAYER_STATS3  @"M.YOSHIDA",        LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define JAPAN_PLAYER_STATS4  @"G.SHODI",         LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, WEAK_STATS
#define JAPAN_PLAYER_STATS5  @"G.SHIBASAKI",     LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, MEDIUM_STATS
#define JAPAN_PLAYER_STATS6  @"S.NAKAJIMA",        LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define JAPAN_PLAYER_STATS7  @"M.HASEBE",      LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, SUPER_EXTRA_STRONG_STATS
#define JAPAN_PLAYER_STATS8  @"S.KAGAWA",        LIGHT_PLAYER_DARK_HAIR,     @STRIKER, EXTRA_STRONG_STATS
#define JAPAN_PLAYER_STATS9  @"G.HARAGUCI",       LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS
#define JAPAN_PLAYER_STATS10 @"Y.NAGATOMO",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, WEAK_STATS
#define JAPAN_PLAYER_STATS11 @"W.ENDO",       LIGHT_PLAYER_BLK_HAIR,     @DEFENDER, STRONG_STATS
#define JAPAN_PLAYER_STATS12 @"S.MUROYA",       LIGHT_PLAYER_DARK_HAIR,     @DEFENDER, STRONG_STATS
#define JAPAN_PLAYER_STATS13 @"M.HASABE",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define JAPAN_PLAYER_STATS14 @"H.YAMGUCHI",     LIGHT_PLAYER_BLK_HAIR,     @MIDFIELD, STRONG_STATS
#define JAPAN_PLAYER_STATS15 @"R.DOAN",      LIGHT_PLAYER_DARK_HAIR,     @MIDFIELD, STRONG_STATS
#define JAPAN_PLAYER_STATS16 @"S.OKAZAKI",         LIGHT_PLAYER_BLK_HAIR,     @STRIKER, STRONG_STATS
#define JAPAN_PLAYER_STATS17 @"Y.MUTO",      LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS
#define JAPAN_PLAYER_STATS18 @"Y.OSAKO",            LIGHT_PLAYER_DARK_HAIR,     @STRIKER, STRONG_STATS

// WALES
#define WALES_PLAYER_STATS1   @"W.HENNESE",        WHITE_PLAYER_KEEPER_BROWN_HAIR,            @KEEPER, STRONG_STATS
#define WALES_PLAYER_STATS2   @"C.ROBERTS",    LIGHT_PLAYER_DARK_HAIR,             @DEFENDER, MEDIUM_STATS
#define WALES_PLAYER_STATS3   @"A.WILLIAMS",      LIGHT_PLAYER_DARK_HAIR,             @DEFENDER, WEAK_STATS
#define WALES_PLAYER_STATS4   @"C.GUNTER",        DARK_PLAYER_BLACK_HAIR,             @DEFENDER, STRONG_STATS
#define WALES_PLAYER_STATS5   @"J.ALLEN",     WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, WEAK_STATS
#define WALES_PLAYER_STATS6   @"A.RAMSEY",        LIGHT_PLAYER_DARK_HAIR,             @MIDFIELD, EXTRA_STRONG_STATS
#define WALES_PLAYER_STATS7   @"S.VOKES",   DARK_PLAYER_BLACK_HAIR,             @STRIKER, STRONG_STATS
#define WALES_PLAYER_STATS8   @"H.KANU",       WHITE_PLAYER_LIGHT_BROWN_HAIR,       @STRIKER, EXTRA_STRONG_STATS
#define WALES_PLAYER_STATS9   @"G.BALE",        WHITE_PLAYER_LIGHT_BROWN_HAIR,       @STRIKER, SUPER_EXTRA_STRONG_STATS
#define WALES_PLAYER_STATS10  @"C.MEPHAM",    WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, MEDIUM_STATS
#define WALES_PLAYER_STATS11  @"B.DAVIES",      LIGHT_PLAYER_DARK_HAIR,             @DEFENDER, STRONG_STATS
#define WALES_PLAYER_STATS12  @"J.CHESTER",       WHITE_PLAYER_DARK_BROWN_HAIR,       @DEFENDER, WEAK_STATS
#define WALES_PLAYER_STATS13  @"H.WILSON",    WHITE_PLAYER_DARK_BROWN_HAIR,       @MIDFIELD, MEDIUM_STATS
#define WALES_PLAYER_STATS14  @"D.JAMES",   DARK_PLAYER_BLACK_HAIR,             @MIDFIELD, STRONG_STATS
#define WALES_PLAYER_STATS15  @"E.AMPADU",   WHITE_PLAYER_LIGHT_BROWN_HAIR,       @MIDFIELD, WEAK_STATS
#define WALES_PLAYER_STATS16  @"S.VOKES",    WHITE_PLAYER_LIGHT_BROWN_HAIR,             @STRIKER, STRONG_STATS
#define WALES_PLAYER_STATS17  @"T.LAWRENCE",     DARK_PLAYER_BLACK_HAIR,       @STRIKER, WEAK_STATS
#define WALES_PLAYER_STATS18  @"D.BROOKS",    WHITE_PLAYER_LIGHT_BROWN_HAIR,             @MIDFIELD, STRONG_STATS



#endif /* England_h */
